name: "CinemaJava project"

volumes:
  cinemajava-db-volume:
  cinemajava-pgadmin-volume:
  cinemajava-rabbitmq_data-volume:

services:
  cinemajava-db-postgres:
    image: postgres:17-alpine
    container_name: cinemajava-db-postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_USER_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB_NAME}

    volumes:
      - cinemajava-db-volume:/var/lib/postgresql/data

    healthcheck:
      test: >
        bash -c "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} &&
        psql -U $${POSTGRES_USER} -d $${POSTGRES_DB} -c 'SELECT 1'"
      interval: 10s
      timeout: 5s
      retries: 5

    networks:
      - cinemajava-network

  cinemajava-pgadmin:
    build: pgadmin
    container_name: cinemajava-pgadmin
    restart: always
    user: root
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
      - PGADMIN_CONFIG_SERVER_MODE=False
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_USER_PASSWORD=${POSTGRES_USER_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB_NAME}
      - POSTGRES_HOST=cinemajava-db-postgres
      - POSTGRES_PORT=${POSTGRES_PORT}
      - PGADMIN_SERVER_NAME=${PGADMIN_SERVER_NAME}

    volumes:
      - cinemajava-pgadmin-volume:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - cinemajava-network
    depends_on:
      cinemajava-db-postgres:
        condition: service_healthy

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: cinemajava-rabbitmq
    ports:
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    volumes:
      - cinemajava-rabbitmq_data-volume:/var/lib/rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - cinemajava-network

networks:
  cinemajava-network:
    driver: bridge
    name: cinemajava-network